### PR TITLE
Command line arguments fix

### PR DESCRIPTION
**Pull request by pgaref**
- Problem: I wanted to run a seep-wroker or a seep-master from command line using a static configuration file like: ./seep-worker --properties.file=/home/pg1712/my-config/worker1.properties. As it tourned out the properties file was not being read because by default it was expecting a local file with name properties.file. 
- Solution: I fixed that reading the prorties-filename form the command line, given by the user and then changed the file priorities to have higher priority than command line arguments - otherwise they are going to be ignored every time! I am not sure what was the idea here but the way it works now makes more sense  to me.

### CODE REVIEW

**Comment by raulcf** [comment]
I understand this pull request is solving two problems, one is reading from files with arbitrary names, and the other is permitting command line arguments to have a higher priority than file, is this correct?

**Comment by pgaref** [comment]
That's correct with the only difference that file arguments have higher prioroty than command line. The only reason for that is some commandLine properties have default values that overwrite the ones in the file properties. If we think command line arguments should always have higher priority I can find a workaround.

**Comment by raulcf** [comment]
Ah, thanks for detecting this error! This is important.

> If we think command line arguments should always have higher priority I can find a workaround.

I think so, it is always easier to overwrite command line arguments than opening a file editing saving, etc:  Command line arguments should have higher priority.

> The only reason for that is some commandLine properties have default values 
> that overwrite the ones in the file properties

Ok, this is the problem to solve. The app won't run unless a minimum amount of parameters (those that are mandatory) are provided. We have to find a reasonable way of enforcing this. The invariant should be at all times that command lines arguments are higher priority than file.properties. 

In general a solution should look like:
The app will always read a default config.properties (whatever name it has) unless a command line argument specifies other config.properties file, in which case the app will read that one. Once a config.properties has been read, then the app will overwrite properties with values provided through command line, which are higher priority. At this point the app should validate that all mandatory fields have been configured.

Does that make sense?

**Comment by pgaref** [comment]
> Does that make sense?

Totally makes sense. I am on it!

**Comment by pgaref** [comment]
Updated code working as discussed. Please check :)

**Comment by raulcf** [comment]
Hi, please make sure lsds is in the latest state before creating this pull request. That is, lsds master must be synchronized with the latest changes of raulcf. Then, the branch where you created the fix must incorporate all changes from master. Then it is safe to create a pull request.

**Comment by pgaref** [comment]
The changes are completely independent but I updated LSDS master anyway and used a merge to synch this branch with the master. :+1:

**Comment by raulcf** [comment]
Looks great thanks!

**Pull request merged**
