### PR TITLE
Updated Memory Management Policy

### PR DESCRIPTION
**Pull request by WJCIV**
This recomputes the cost of evicting each Dataset after each stage instead of relying on the value calculated when the Dataset is first encountered. Since the calculation relies on the number of times a Dataset is expected to be accessed, it makes sense to use the number of times remaining instead of including past accesses. This is actually done with less complex datastructures, so the code is simpler.

This does significantly positively impact the hit/miss ratio. Hit/miss ratios for mb2 with a selectivity of 1, fanout = fanout2 = 3, and 4 datasets fitting in memory:
LRU - .2959
old AMM (ea1ff1e) - .512
new AMM (3b1e33f) - .5553

Also, I just managed a successful run with mb1 where the fanout equaled the number of workers, which was throwing all sorts of exceptions before. I'm not sure which commit fixed that, or even if it is fixed in all cases, but that seems like a bonus.

### CODE REVIEW

**Comment by raulcf** [comment]
Is this the most updated pull request? Do we want to merge to master or keep it in a new branch for now until we can run everything successfully?

**Comment by WJCIV** [comment]
This is the newest. I think it can run everything more-or-less successfully. For some reason the source Dataset is treated properly in some workers, but not in others, which is still an improvement over the current master.

 wc -l also reveals that the logs from different workers are different lengths, but I haven't tracked down what the actual differences are yet. It's probably related to whatever is non-deterministic about whether the source Dataset appears in dataset_expected_count.

**Comment by raulcf** [comment]
Ok, then, is it safer to create the pull request to a different branch? or do you want me to merge here instead and move on?

**Comment by WJCIV** [comment]
Whatever makes sense to you. Everything moving forward should be built on top of this, but if you feel safer keeping it separated until everything is fixed that works for me.

**Comment by raulcf** [comment]
Merged, thanks!

**Pull request merged**
